"""
仓储接口定义 - 数据持久化的抽象契约
"""

from abc import ABC, abstractmethod
from typing import Optional, Self

from ..models.story import Story
from ..models.character import Character
from ..models.chapter import Chapter
from ..models.worldbuilding import WorldBuilding
from ..models.knowledge_triple import KnowledgeTriple
from ..models.outline import Outline


class StoryRepository(ABC):
    @abstractmethod
    def save(self, story: Story) -> Story: ...
    @abstractmethod
    def get(self, story_id: str) -> Optional[Story]: ...
    @abstractmethod
    def delete(self, story_id: str) -> bool: ...
    @abstractmethod
    def list_all(self) -> list[dict]: ...
    @abstractmethod
    def exists(self, story_id: str) -> bool: ...


class CharacterRepository(ABC):
    @abstractmethod
    def save(self, character: Character) -> Character: ...
    @abstractmethod
    def get(self, character_id: str) -> Optional[Character]: ...
    @abstractmethod
    def list_by_story(self, story_id: str) -> list[Character]: ...
    @abstractmethod
    def delete(self, character_id: str) -> bool: ...


class ChapterRepository(ABC):
    @abstractmethod
    def save(self, chapter: Chapter) -> Chapter: ...
    @abstractmethod
    def get(self, chapter_id: str) -> Optional[Chapter]: ...
    @abstractmethod
    def list_by_story(self, story_id: str) -> list[Chapter]: ...
    @abstractmethod
    def delete(self, chapter_id: str) -> bool: ...
    @abstractmethod
    def max_chapter_number(self, story_id: str) -> int: ...


class WorldBuildingRepository(ABC):
    @abstractmethod
    def save(self, wb: WorldBuilding) -> WorldBuilding: ...
    @abstractmethod
    def get(self, wb_id: str) -> Optional[WorldBuilding]: ...
    @abstractmethod
    def list_by_story(self, story_id: str) -> list[WorldBuilding]: ...
    @abstractmethod
    def delete(self, wb_id: str) -> bool: ...


class KnowledgeTripleRepository(ABC):
    @abstractmethod
    def save(self, triple: KnowledgeTriple) -> KnowledgeTriple: ...
    @abstractmethod
    def list_by_story(self, story_id: str) -> list[KnowledgeTriple]: ...
    @abstractmethod
    def search(self, story_id: str, query: str) -> list[KnowledgeTriple]: ...
    @abstractmethod
    def delete_by_story(self, story_id: str): ...


class OutlineRepository(ABC):
    @abstractmethod
    def save(self, outline: Outline) -> Outline: ...
    @abstractmethod
    def get_by_story(self, story_id: str) -> Optional[Outline]: ...
    @abstractmethod
    def delete(self, outline_id: str) -> bool: ...


class UnitOfWork(ABC):
    """工作单元 - 确保事务一致性"""

    @abstractmethod
    def __enter__(self) -> Self: ...
    @abstractmethod
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    @abstractmethod
    def commit(self) -> None: ...
    @abstractmethod
    def rollback(self) -> None: ...
